# Generated by Django 6.1.1 on 2026-09-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(default='Queen bed', max_length=60)),
                ('size_sqm', models.PositiveSmallIntegerField(default=25, verbose_name='size (m²)')),
                ('image', models.ImageField(blank=True, upload_to='room_types/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive types are hidden from the public site.')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity')),
            ],
            options={
                'ordering': ['nightly_rate'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('floor', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Needs cleaning'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['floor', 'number'],
            },
        ),
    ]
